name: PHP Static code checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: OSKAR-PHP-CS-Fixer
      uses: OskarStark/php-cs-fixer-ga@3.22.0
      with:
        args: --diff --dry-run
